modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/blockrunner/issues"
[[mods]]
modId="blockrunner"
version="${file.jarVersion}"
displayName="BlockRunner"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/blockrunner"
logoFile="blockrunner_logo.png"
credits="The Forge team and community for the help and resources."
authors="Mapper"
description="BlockRunner allows moving faster on specific blocks that can be configured so building roads can be actually useful."

[[dependencies.blockrunner]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.blockrunner]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"
